#!/usr/bin/env python3
"""Fetch a public Notion page (via r.jina.ai Markdown) and dump its schedule
table as schedule.json.

The Notion page is rendered server-side by r.jina.ai and returned as Markdown:
  ... "Isi tabel" ...
  Tanggal
  17 Agustus 2026
  Training
  Training 1
  Materi
  item A
  item B
  Registrasi
  [Registrasi](https://lynk.id/dikodeworks/n08485j53pn0)
  ...

A field may contain MORE THAN ONE value line (e.g. Materi lists several
materials). Consecutive value lines for the same key are joined with \n.

Configuration via env vars:
  NOTION_PAGE_ID   (required) e.g. 3d76fa858bba80678c5ad21fda12a21f
  NOTION_HOST      (optional)  default teguhpm.notion.site
  OUTPUT           (optional)  default schedule.json

Safe to run anywhere: python3, no third-party dependencies.
"""

import json
import os
import re
import sys
import urllib.request

PAGE_ID = os.environ.get("NOTION_PAGE_ID", "").strip().replace("-", "")
HOST = os.environ.get("NOTION_HOST", "teguhpm.notion.site").strip()
OUTPUT = os.environ.get("OUTPUT", "schedule.json").strip()

EXPECTED_COLUMNS = ["Tanggal", "Training", "Materi", "Waktu", "Lokasi", "Biaya", "Registrasi"]
OUTPUT_COLUMNS = ["Tanggal", "Training", "Waktu", "Lokasi", "Biaya", "Registrasi"]


def fetch_markdown():
    """Fetch the public Notion page via r.jina.ai.

    NOTE: deliberately NO unique cache-busting query param. r.jina.ai treats a
    stream of unique URLs from the same domain as a DDoS and returns 403
    "AbuseAlleviationError", which blocked the whole pipeline. A stable URL is
    cached and re-fetched by r.jina.ai, which is good enough for the 5-minute
    refresh cadence of the GitHub Action.
    """
    url = f"https://r.jina.ai/https://{HOST}/" + PAGE_ID
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "*/*",
            "User-Agent": "Mozilla/5.0 (compatible; dikodeworks-schedule/1.0)",
            "X-Timeout": "30",
        },
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return resp.read().decode("utf-8", errors="replace")


def parse(text):
    """Mirror of the JS parseNotionMarkdown in index.html so schedule.json and
    the live browser render always agree. Layout-agnostic: reacts to the field
    labels (Tanggal / Training / Materi / Waktu / Lokasi / Biaya / Registrasi)
    wherever they appear, joined as key then value lines. A repeated key starts
    a new row, and Notion database row-number headings (### 001 / 001) are
    skipped so they never leak into cell values."""
    KEYS = [c.lower() for c in EXPECTED_COLUMNS]
    lines = [l.strip() for l in text.split("\n") if l]
    start = next((i for i, l in enumerate(lines) if l.lower() == "isi tabel"), -1)
    if start == -1:
        return list(OUTPUT_COLUMNS), []

    link_re = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
    row_marker = re.compile(r"^#{0,6}\s*[0-9]{1,6}\s*$")
    num_marker = re.compile(r"^[0-9]{3}$")

    rows = []
    row = {}
    current_key = None

    def flush():
        nonlocal row
        if not row:
            return
        rows.append(dict(row))
        row = {}

    for line in lines[start + 1:]:
        if row_marker.match(line) or num_marker.match(line):
            continue
        low = line.lower()
        if low in KEYS:
            if low in row:
                flush()  # repeated key → new row
            current_key = low
        else:
            if current_key is None:
                continue
            m = link_re.match(line)
            value = m.group(1) if m else line
            link = m.group(2) if m else None
            if current_key in row:
                row[current_key]["v"] += "\n" + value
                if link:
                    row[current_key]["link"] = link
            else:
                row[current_key] = {"v": value, "link": link}
    flush()
    return list(OUTPUT_COLUMNS), rows


def normalize(rows, headers):
    entries = []
    for row in rows:
        entry = []
        for h in headers:
            cell = row.get(h.lower(), {"v": "", "link": None})
            entry.append({"v": cell.get("v", ""), "link": cell.get("link")})
        entries.append(entry)
    return entries


def main():
    if not PAGE_ID:
        sys.exit("NOTION_PAGE_ID is required")
    text = fetch_markdown()
    headers, rows = parse(text)
    document = {
        "source": f"https://{HOST}/" + PAGE_ID,
        "columns": headers,
        "rows": normalize(rows, headers),
        "note": "generated by scripts/build_schedule.py via r.jina.ai from public Notion page",
    }
    # Never clobber a good snapshot with an empty/failed parse (e.g. r.jina.ai
    # returning an abuse/error page). Fail the job so the previous file stays.
    if not document["rows"]:
        sys.exit("schedule parse produced no rows; keeping the previous snapshot")
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        json.dump(document, fh, ensure_ascii=False, indent=2)
    print(f"wrote {OUTPUT}: {len(document['rows'])} rows, {len(headers)} cols")


if __name__ == "__main__":
    main()