#!/usr/bin/env python3
"""Fetch a public Notion page (via r.jina.ai Markdown) and dump its schedule
table as schedule.json.

The Notion page is rendered server-side by r.jina.ai and returned as Markdown:
  ... "Isi tabel" ...
  Tanggal
  17 Agustus 2026
  Training
  Training 1
  Materi
  item A
  item B
  Registrasi
  [Registrasi](https://lynk.id/dikodeworks/n08485j53pn0)
  ...

A field may contain MORE THAN ONE value line (e.g. Materi lists several
materials). Consecutive value lines for the same key are joined with \n.

Configuration via env vars:
  NOTION_PAGE_ID   (required) e.g. 3d76fa858bba80678c5ad21fda12a21f
  NOTION_HOST      (optional)  default teguhpm.notion.site
  OUTPUT           (optional)  default schedule.json

Safe to run anywhere: python3, no third-party dependencies.
"""

import json
import os
import re
import sys
import time
import urllib.request

PAGE_ID = os.environ.get("NOTION_PAGE_ID", "").strip().replace("-", "")
HOST = os.environ.get("NOTION_HOST", "teguhpm.notion.site").strip()
OUTPUT = os.environ.get("OUTPUT", "schedule.json").strip()

EXPECTED_COLUMNS = ["Tanggal", "Training", "Materi", "Waktu", "Lokasi", "Biaya", "Registrasi"]
_lower = [c.lower() for c in EXPECTED_COLUMNS]


def fetch_markdown():
    url = f"https://r.jina.ai/https://{HOST}/" + PAGE_ID + "?generated=" + str(int(time.time()))
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "*/*",
            "User-Agent": "Mozilla/5.0 (compatible; dikodeworks-schedule/1.0)",
            "X-Timeout": "30",
        },
    )
    with urllib.request.urlopen(req, timeout=90) as resp:
        return resp.read().decode("utf-8", errors="replace")


def parse(text):
    lines = [l.strip() for l in text.split("\n")]
    start = next((i for i, l in enumerate(lines) if l.lower() == "isi tabel"), -1)
    if start == -1:
        return EXPECTED_COLUMNS, []

    link_re = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")
    headers = []
    rows = []
    row = None
    pending = None

    def push(val):
        nonlocal row, pending
        if pending is None:
            return
        ci = _lower.index(pending)
        m = link_re.match(val)
        value = m.group(1) if m else val
        link = m.group(2) if m else None
        if row is None:
            row = [None] * len(headers)
        if row[ci] is None:
            row[ci] = {"v": value, "link": link}
        else:
            row[ci]["v"] += "\n" + value
            if link:
                row[ci]["link"] = link
        if all(row):
            rows.append(row)
            row = None
            pending = None

    # Build header list from the FIRST occurrence of the key/value pairs; use
    # EXPECTED_COLUMNS order so output is stable and matches the site.
    headers = list(EXPECTED_COLUMNS)

    for i in range(start + 1, len(lines)):
        l = lines[i]
        if not l:
            continue
        low = l.lower()
        if low in _lower:
            pending = low
        else:
            push(l)
    return headers, rows


def normalize(rows, headers):
    entries = []
    for row in rows:
        entry = []
        for h in headers:
            cell = row[_lower.index(h.lower())]
            entry.append({"v": cell.get("v", ""), "link": cell.get("link")})
        entries.append(entry)
    return entries


def main():
    if not PAGE_ID:
        sys.exit("NOTION_PAGE_ID is required")
    text = fetch_markdown()
    headers, rows = parse(text)
    document = {
        "source": f"https://{HOST}/" + PAGE_ID,
        "columns": headers,
        "rows": normalize(rows, headers),
        "note": "generated by scripts/build_schedule.py via r.jina.ai from public Notion page",
    }
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        json.dump(document, fh, ensure_ascii=False, indent=2)
    print(f"wrote {OUTPUT}: {len(document['rows'])} rows, {len(headers)} cols")


if __name__ == "__main__":
    main()